-- 샘플 데이터
DROP TABLE SAMPLE_TBL;
CREATE TABLE SAMPLE_TBL(
    NAME VARCHAR2(10 BYTE),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3)
);

INSERT INTO SAMPLE_TBL(NAME, KOR, ENG, MAT) VALUES(NULL, 100,100,100);
INSERT INTO SMAPLE_TBL(NAME, KOR, ENG, MAT) VALUES('정숙', NULL, 90, 90);
INSERT INTO SMAPLE_TBL(NAME, KOR, ENG, MAT) VALUES('미희', 80, NULL, 90);
INSERT INTO SMAPLE_TBL(NAME, KOR, ENG, MAT) VALUES('철수', 70, 70, NULL);
COMMIT;