DROP TABLE SUPPORT_TBL;
DROP TABLE STU_TBL;
DROP TABLE SUB_TBL;

CREATE TABLE STU_TBL(
    STU_NO VARCHAR2(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2(12 BYTE),
    STU_AGE NUMBER,
    CONSTRAINT PK_STU_NO PRIMARY KEY(STU_NO)
);

CREATE TABLE SUB_TBL(
    SUB_CODE VARCHAR2(3 BYTE) NOT NULL,
    SUB_NAME VARCHAR2(12 BYTE),
    PROF_NAME VARCHAR2(12 BYTE),
    CONSTRAINT PK_SUB_CODE PRIMARY KEY(SUB_CODE)
);

CREATE TABLE SUPPORT_TBL(
    COMM_NO NUMBER NOT NULL,
    STU_NO VARCHAR2(5 BYTE) NOT NULL,
    SUB_CODE VARCHAR2(3 BYTE) NOT NULL,
    CONSTRAINT PK_COMM_NO PRIMARY KEY(COMM_NO),
    CONSTRAINT FK_STU_NO FOREIGN KEY(STU_NO) REFERENCES STU_TBL(STU_NO) ON DELETE CASCADE,
    CONSTRAINT FK_SUB_CODE FOREIGN KEY(SUB_CODE) REFERENCES SUB_TBL(SUB_CODE) ON DELETE CASCADE
);